keys:
  users:
    - &user_sam_server age1nfxh2pew7s93hl9d605ce2lg25u5jyqqa8phmqtalppzzre7rvmss8qaxg
    - &user_sam_framework age1sunx385u98xm25pgjhm85ntaqze3g8m0599rr0lyn6hvc9wrxdcssd9g4f
  hosts:
    - &host_backup age1mhlsppkd6nutvdmaqde8k0cmv6q7vr8vt9lszp2k8gt799k87pdssu0jy2
    - &host_framework age13p3w43lx9hj6znla2wvq6t8ndrr4vj407ymc9zmjt4upk0nlpupse574dk
    - &host_nixos_anywhere age1kd9jcgmpmsurmv0h76mnx67j8sgvqrdwn0g54fwgmku22m9w43js8usxud
    - &host_server_new age1vk35vw3rngexeqqdast8jvpmesf8ttpmcl6fqcg9c68a68wqn9hsr2cv5n
    - &host_server age19efdl5tlu0nk6l7x43hrnu6tf4w5s92565gz6yfa25hwy7uwruhssvys74
    - &host_thinkpad age19rnfkm92axavs9c98qryne6r9jpplv5khvdvkakflau6z72pxgaq7yk06p
    - &host_google age1m2v6zphz5jl5mt4lke53ak0shzv8n9z0ap47jxl0nmw24rl854uq4rt60y
  microvms:
    - &microvm_hermes  age16wn9de6cg4tz5x0a3sh6q5jzwwmupal4khvfrw7wm4m8ge6kxa5q6ramp6

creation_rules:
  - path_regex: ^secrets/hermes\.yaml$
    key_groups:
      - age:
          - *microvm_hermes
          - *user_sam_framework
          - *host_server_new
  - path_regex: ^secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_sam_server
          - *user_sam_framework
          - *host_server
          - *host_backup
          - *host_framework
          - *host_nixos_anywhere
          - *host_server_new
          - *host_thinkpad
          - *host_google
