keys:
  users:
    - &user_sam_server age1nfxh2pew7s93hl9d605ce2lg25u5jyqqa8phmqtalppzzre7rvmss8qaxg
    - &user_sam_framework age1sunx385u98xm25pgjhm85ntaqze3g8m0599rr0lyn6hvc9wrxdcssd9g4f
  hosts:
    - &host_backup age1qmw2h2hzvjprgyr94mfg4eljm5zg0zjfkxf4uwyp6k5xhmcxmerspvcmqe
    - &host_framework age13p3w43lx9hj6znla2wvq6t8ndrr4vj407ymc9zmjt4upk0nlpupse574dk
    - &host_nixos_anywhere age1kd9jcgmpmsurmv0h76mnx67j8sgvqrdwn0g54fwgmku22m9w43js8usxud
    - &host_server_new age1vk35vw3rngexeqqdast8jvpmesf8ttpmcl6fqcg9c68a68wqn9hsr2cv5n
    - &host_server age19efdl5tlu0nk6l7x43hrnu6tf4w5s92565gz6yfa25hwy7uwruhssvys74
    - &host_thinkpad age19rnfkm92axavs9c98qryne6r9jpplv5khvdvkakflau6z72pxgaq7yk06p

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_sam_server
          - *user_sam_framework
          - *host_server
          - *host_backup
          - *host_framework
          - *host_nixos_anywhere
          - *host_server_new
          - *host_thinkpad
